version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_colaboradores
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: colaboradores_ipdv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_colaboradores
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=colaboradores_ipdv
      - JWT_SECRET=secret_key
      - JWT_EXPIRES_IN=60m

volumes:
  postgres_data:
